_target_: finsde.core.FinSDELightningModule
model:
  _target_: finsde.models.discrete_sde.DiscreteLatentSDE
  data_size: ${eval:'len(${...datamodule.feat_columns})'}
  latent_size: 6
  context_size: 32
  hidden_size: 64
  output_size: ${eval:'len(${...datamodule.pred_columns})'}
  context_mode: "constant"
  forecast_mode: "prior"
  posterior_samples: 8
optimizer_partial:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
lr_scheduler_partial: 
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 20
  factor: 0.3
  min_lr: 1e-5
  cooldown: 5
lr_scheduler_cfg:
  monitor: train_loss
