_target_: finsde.core.FinLightningModule
model:
  _target_: finsde.models.lstm.LSTMModel
  input_size: ${eval:'len(${...datamodule.feat_columns})'}
  hidden_size: 100
  output_size: ${eval:'len(${...datamodule.pred_columns}) * ${...datamodule.pred_horizon}'}
  n_layers: 4
  dropout: 0.2
loss:
  _target_: torch.nn.MSELoss
optimizer_partial:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
lr_scheduler_partial: 
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 20
  factor: 0.3
  min_lr: 1e-5
  cooldown: 5
lr_scheduler_cfg:
  monitor: train_loss