_target_: finsde.core.FinLightningModule
model:
  _target_: finsde.models.transformer.TransformerModel
  n_encoder_layers: 4
  n_decoder_layers: 4
  n_heads: 8
  d_model: 32
  d_ff: 1024
  input_size: ${eval:'len(${...datamodule.feat_columns})'}
  output_size: ${eval:'len(${...datamodule.pred_columns}) * ${...datamodule.pred_horizon}'}
  dropout: 0.1
  activation: "gelu"
loss:
  _target_: torch.nn.MSELoss
optimizer_partial:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
lr_scheduler_partial: 
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 5
  factor: 0.3
  min_lr: 1e-6
  cooldown: 5
lr_scheduler_cfg:
  monitor: train_loss