checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "results/${...run_name}/checkpoints"
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  every_n_epochs: ${...trainer.check_val_every_n_epoch}
  filename: "{epoch}-{val_loss:.2f}"
