checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "results/${...run_name}/checkpoints"
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  every_n_epochs: ${...trainer.check_val_every_n_epoch}
  filename: "{epoch}-{val_loss:.2f}"
validation_callback:
  _target_: finsde.utils.callbacks.R2Callback
  eval_dim: 0
  log_prefix: ""
  split: "val"
  predict_kwargs:
    n_samples: 1
test_callback:
  _target_: finsde.utils.callbacks.R2Callback
  eval_dim: 0
  log_prefix: ""
  split: "test"
  predict_kwargs:
    n_samples: 1
recurrent_eval_callback:
  _target_: finsde.utils.callbacks.RecurrentPredR2Callback
  eval_dim: 0
  n_pred_steps: [1, 3, 10]
  log_prefix: ""
  split: "test"
  predict_kwargs:
    n_samples: 1
  