checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "results/${...run_name}/checkpoints"
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  every_n_epochs: ${...trainer.check_val_every_n_epoch}
  filename: "{epoch}-{val_loss:.2f}"
validation_callback:
  _target_: finsde.utils.callbacks.R2Callback
  eval_dim: [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150]
  log_prefix: ""
  split: "val"
  predict_kwargs:
    n_samples: 8
test_callback:
  _target_: finsde.utils.callbacks.R2Callback
  eval_dim: [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150]
  log_prefix: ""
  split: "test"
  predict_kwargs:
    n_samples: 8
recurrent_eval_callback:
  _target_: finsde.utils.callbacks.RecurrentPredR2Callback
  eval_dim: [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150]
  n_pred_steps: [1, 3, 10]
  log_prefix: ""
  split: "test"
  predict_kwargs:
    n_samples: 8
  
