checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "results/${...run_name}/checkpoints"
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  every_n_epochs: ${...trainer.check_val_every_n_epoch}
  filename: "{epoch}-{val_loss:.2f}"
validation_callback:
  _target_: finsde.utils.callbacks.R2Callback
  eval_dim: [3, 12, 21, 30, 39, 48, 57, 66, 75, 84, 93, 102, 111, 120, 129, 138, 147, 156, 165, 174, 183, 192, 201, 210, 219, 228]
  log_prefix: ""
  split: "val"
test_callback:
  _target_: finsde.utils.callbacks.R2Callback
  eval_dim: [3, 12, 21, 30, 39, 48, 57, 66, 75, 84, 93, 102, 111, 120, 129, 138, 147, 156, 165, 174, 183, 192, 201, 210, 219, 228]
  log_prefix: ""
  split: "test"
recurrent_eval_callback:
  _target_: finsde.utils.callbacks.RecurrentPredR2Callback
  eval_dim: [3, 12, 21, 30, 39, 48, 57, 66, 75, 84, 93, 102, 111, 120, 129, 138, 147, 156, 165, 174, 183, 192, 201, 210, 219, 228]
  n_pred_steps: [1, 3, 10]
  log_prefix: ""
  split: "test"
  