_target_: finsde.utils.dataloader.SingleStockDataModule
feat_columns: ["Close", "Volume", "Open", "High", "Low", "Scaled_sentiment"]
pred_columns: ["Close"]
pred_window: 50
pred_horizon: 3
standardize: true
train_val_test_split: [0.85, 0.15, 0.0]
batch_size: 256
data_dir: "../../data/full_history/"

csv_files: 
  - 'AAL.csv'
  - 'AAPL.csv'
  - 'ABBV.csv'
  - 'AMD.csv'
  - 'AMGN.csv'
  - 'AMZN.csv'
  - 'BABA.csv'
  - 'BHP.csv'
  - 'BIDU.csv'
  - 'BIIB.csv'
  - 'BRK-B.csv'
  - 'C.csv'
  - 'CAT.csv'
  - 'CMCSA.csv'
  - 'CMG.csv'
  - 'COP.csv'
  - 'COST.csv'
  - 'CRM.csv'
  - 'CVX.csv'
  - 'DAL.csv'
  - 'DIS.csv'
  - 'EBAY.csv'
  - 'GE.csv'
  - 'GILD.csv'
  - 'GLD.csv'
  - 'GOOG.csv'
  - 'GSK.csv'
  - 'INTC.csv'
  - 'KO.csv'
  - 'MRK.csv'
  - 'MSFT.csv'
  - 'MU.csv'
  - 'NKE.csv'
  - 'NVDA.csv'
  - 'ORCL.csv'
  - 'PEP.csv'
  - 'PYPL.csv'
  - 'QCOM.csv'
  - 'QQQ.csv'
  - 'SBUX.csv'
  - 'T.csv'
  - 'TGT.csv'
  - 'TM.csv'
  - 'TSLA.csv'
  - 'TSM.csv'
  - 'USO.csv'
  - 'V.csv'
  - 'WFC.csv'
  - 'WMT.csv'
  - 'XLF.csv'

eval_csv_files:
  - 'AMD.csv'
  - 'GOOG.csv'
  - 'KO.csv'
  - 'TSM.csv'
  - 'WMT.csv'